# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/greghaynes/Projects/kdelicious

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/greghaynes/Projects/kdelicious

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/greghaynes/Projects/kdelicious/CMakeFiles /home/greghaynes/Projects/kdelicious/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/greghaynes/Projects/kdelicious/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named kdelicious

# Build rule for target.
kdelicious: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kdelicious
.PHONY : kdelicious

# fast build rule for target.
kdelicious/fast:
	$(MAKE) -f CMakeFiles/kdelicious.dir/build.make CMakeFiles/kdelicious.dir/build
.PHONY : kdelicious/fast

#=============================================================================
# Target rules for targets named kdelicious_automoc

# Build rule for target.
kdelicious_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kdelicious_automoc
.PHONY : kdelicious_automoc

# fast build rule for target.
kdelicious_automoc/fast:
	$(MAKE) -f CMakeFiles/kdelicious_automoc.dir/build.make CMakeFiles/kdelicious_automoc.dir/build
.PHONY : kdelicious_automoc/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

# target to build an object file
createbookmarkdialog.o:
	$(MAKE) -f CMakeFiles/kdelicious.dir/build.make CMakeFiles/kdelicious.dir/createbookmarkdialog.o
.PHONY : createbookmarkdialog.o

# target to preprocess a source file
createbookmarkdialog.i:
	$(MAKE) -f CMakeFiles/kdelicious.dir/build.make CMakeFiles/kdelicious.dir/createbookmarkdialog.i
.PHONY : createbookmarkdialog.i

# target to generate assembly for a file
createbookmarkdialog.s:
	$(MAKE) -f CMakeFiles/kdelicious.dir/build.make CMakeFiles/kdelicious.dir/createbookmarkdialog.s
.PHONY : createbookmarkdialog.s

# target to build an object file
kdelicious_automoc.o:
	$(MAKE) -f CMakeFiles/kdelicious.dir/build.make CMakeFiles/kdelicious.dir/kdelicious_automoc.o
.PHONY : kdelicious_automoc.o

# target to preprocess a source file
kdelicious_automoc.i:
	$(MAKE) -f CMakeFiles/kdelicious.dir/build.make CMakeFiles/kdelicious.dir/kdelicious_automoc.i
.PHONY : kdelicious_automoc.i

# target to generate assembly for a file
kdelicious_automoc.s:
	$(MAKE) -f CMakeFiles/kdelicious.dir/build.make CMakeFiles/kdelicious.dir/kdelicious_automoc.s
.PHONY : kdelicious_automoc.s

# target to build an object file
kdeliciousplugin.o:
	$(MAKE) -f CMakeFiles/kdelicious.dir/build.make CMakeFiles/kdelicious.dir/kdeliciousplugin.o
.PHONY : kdeliciousplugin.o

# target to preprocess a source file
kdeliciousplugin.i:
	$(MAKE) -f CMakeFiles/kdelicious.dir/build.make CMakeFiles/kdelicious.dir/kdeliciousplugin.i
.PHONY : kdeliciousplugin.i

# target to generate assembly for a file
kdeliciousplugin.s:
	$(MAKE) -f CMakeFiles/kdelicious.dir/build.make CMakeFiles/kdelicious.dir/kdeliciousplugin.s
.PHONY : kdeliciousplugin.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... kdelicious"
	@echo "... kdelicious_automoc"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... uninstall"
	@echo "... createbookmarkdialog.o"
	@echo "... createbookmarkdialog.i"
	@echo "... createbookmarkdialog.s"
	@echo "... kdelicious_automoc.o"
	@echo "... kdelicious_automoc.i"
	@echo "... kdelicious_automoc.s"
	@echo "... kdeliciousplugin.o"
	@echo "... kdeliciousplugin.i"
	@echo "... kdeliciousplugin.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

